'''
CANVAS_WIDTH = 800
CANVAS_HEIGHT = 600
SIDEBAR_WIDTH = 200
SIDEBAR_HEIGHT = CANVAS_HEIGHT
'''
### MANUAL-EDIT ###
CANVAS_WIDTH = 800
CANVAS_HEIGHT = 600
SIDEBAR_WIDTH = 200
SIDEBAR_HEIGHT = CANVAS_HEIGHT
'''
NODE_INNER_COLOR="purple"
CANVAS_BG="grey"
SIDEBAR_BG="brown"
CONNECTOR_COLOR = "black"
CONNECTOR_EASY_COLOR = "blue"
CONNECTOR_HARD_COLOR = "red"
'''
### AUTO-FILL ###
NODE_INNER_COLOR="purple"
CANVAS_BG="white"
SIDEBAR_BG="grey"
CONNECTOR_COLOR = "black"
CONNECTOR_EASY_COLOR = "blue"
CONNECTOR_HARD_COLOR = "red"
NODE_SIZE = 60
